// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq8FIYAloIj7DcLIuzlXC0JY3GWi-ffCM',
    appId: '1:698029781603:web:c7c4a36adc6ba265a63e56',
    messagingSenderId: '698029781603',
    projectId: 'kejapin-46148',
    authDomain: 'kejapin-46148.firebaseapp.com',
    storageBucket: 'kejapin-46148.firebasestorage.app',
    measurementId: 'G-XNW5L0DVR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgwoXMyOnSuZTbgVOysyEmysDdDnEoj0w',
    appId: '1:698029781603:android:7c1e3fb9f5d89c40a63e56',
    messagingSenderId: '698029781603',
    projectId: 'kejapin-46148',
    storageBucket: 'kejapin-46148.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuBzaQXl2MpdKvbLuQ-QUFq3O5N_iI4uE',
    appId: '1:698029781603:ios:2c3cb99c665177e6a63e56',
    messagingSenderId: '698029781603',
    projectId: 'kejapin-46148',
    storageBucket: 'kejapin-46148.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuBzaQXl2MpdKvbLuQ-QUFq3O5N_iI4uE',
    appId: '1:698029781603:ios:2c3cb99c665177e6a63e56',
    messagingSenderId: '698029781603',
    projectId: 'kejapin-46148',
    storageBucket: 'kejapin-46148.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq8FIYAloIj7DcLIuzlXC0JY3GWi-ffCM',
    appId: '1:698029781603:web:986e9dd48c449289a63e56',
    messagingSenderId: '698029781603',
    projectId: 'kejapin-46148',
    authDomain: 'kejapin-46148.firebaseapp.com',
    storageBucket: 'kejapin-46148.firebasestorage.app',
    measurementId: 'G-G979RZN7P5',
  );
}
